# Blog基本信息
blog_name: 杂记
slogan: 杂记一体，所包甚广，所记者杂，故曰《杂记》。
url: http://blog.wuzhiwei.cn

# 设置头像
avatar: /images/avatar.jpg

# 设置favicon
favicon: /favicon.ico

# 设置关键词
keywords: PHP,JavaScript,Html,Linux,WEB开发,Mac,后端开发,程序员,杂记,随笔,博客,好文,摄影,旅行,网球,blog.wuzhiwei.cn,wuzhiwei.cn

# 设置首页导航
home_nav:
  - name: 主页
    url: http://wuzhiwei.cn
    target_blank: true #不在新页面打开
  - name: Blog
    url: /archives/
    target_blank: false #不在新页面打开
  - name: Github
    url: https://github.com/roferwoo
    target_blank: true #在新页面打开

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

# 设置页面导航样式
page_nav_style: CIRCLE # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 设置盒子是否显示和其显示的文字
toolbox:
  isShow: true # true|fase
  text: 首页

# 搜索页面
search_slogan:
  isShow: true # true|fase
  text: 所包甚广，所记者杂 ~

# 友链页面
link_slogan:
  isShow: true # true|fase
  text: 友链交换可邮件至：roferwoo[at]gmail[dot]com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 打赏一下
  tip: 扫一扫，支持“杂记”
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wx-258.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-zfb.png

# 设置文章标题对齐方式
post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 0553623a66dcdf3168de8ecb48919f53

# Comment service
# disqus_shortname: forsigner
# duoshuo_shortname: forsigner
# gentie_key: d16a7241e7cd4b389584ed8db2a4e8bc

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - "rofer，1989，Autumn。"
    - "一个靠谱的人，Programmer！"
    - "后端开发，常用PHP / Linux / HTML / CSS / JavaScript。"
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@roferwoo"
    text_value_url: https://github.com/roferwoo
  - type: weibo
    icon: icon-weibo
    text_key: 微博
    text_value: "@roferwoo"
    text_value_url: http://weibo.com/roferwoo
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "roferwoo[at]gmail[dot]com"
  - type: location
    icon: icon-location
    text_value: 上海

# 友链
link:
  - name: Enjoy JavaScript
    info: 为者常成，行者常至
    url: http://nanchao.win/
    avatar: http://i4.buimg.com/4851/1bc9a495d3eaad8a.jpg

#project:
  #- type: personal
  #  name: fexo
  #  url: https://github.com/forsigner/fexo
  #  intro: A minimalist design theme for hexo
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo

